name: Push to Server and Build Docker Compose

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    #    strategy:
    #      matrix:
    #        go-version: [ '1.21.6' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 检出完整的git历史记录

      - name: 解压文件 zip 文件
        run: unzip -o ./dist.zip -d ./dist/web


      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.KEY }}
          source: "./dist/web/"
          target: ${{ secrets.PATH }}



